id: P648BFB4E
initial_creation_type: input
source_metadata:
  Title: Viśvaprakāśaḥ
  Editor: Śrī Maheśvara
  Publisher: '-'
  Place of Publication: London
  Year: '1911'
  Viśvaprakāśaḥ:
    Text Version: Romanized
    Input Personnel: Anjana Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:15:27.366304'
last_modified_at: '2022-03-08T17:15:27.366315'
